# For production on VM
version: '3.9'

services:
  database:
    image: postgres:alpine
    container_name: our-backend-database
    hostname: database
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    restart: always
  app:
    image: asia-southeast2-docker.pkg.dev/project-name/docker/our-backend
    container_name: our-backend-app
    build: .
    ports:
      - 80:4000
      - 443:4000
      - 4000:4000
    env_file:
      - .env
    depends_on:
      - database
    restart: always

volumes:
  postgres:
    name: our-backend-database
